parameters:
#    walva_publication.example.class: Walva\PublicationBundle\Example

services:
#    walva_publication.example:
#        class: %walva_publication.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
