walva_supportkot:
    resource: "@WalvaSupportkotBundle/Resources/config/routing.yml"
    prefix:   /

WalvaSupportkotBundle_annee:
        resource: "@WalvaSupportkotBundle/Resources/config/routing/annee.yml"
        prefix:   /annee

WalvaSupportkotBundle_fac:
        resource: "@WalvaSupportkotBundle/Resources/config/routing/fac.yml"
        prefix:   /fac
        
WalvaSupportkotBundle_parrain:
        resource: "@WalvaSupportkotBundle/Resources/config/routing/parrain.yml"
        prefix:   /parrain

WalvaSupportkotBundle_filleul:
        resource: "@WalvaSupportkotBundle/Resources/config/routing/filleul.yml"
        prefix:   /filleul
        
        
# PUBLICATION ---

walvaPublicationBundle_article:
        resource: "@WalvaPublicationBundle/Resources/config/routing/article.yml"
        prefix:   /article

walvaPublicationBundle_image:
        resource: "@WalvaPublicationBundle/Resources/config/routing/image.yml"
        prefix:   /image
        
walvaPublicationBundle_categorie:
        resource: "@WalvaPublicationBundle/Resources/config/routing/categorie.yml"
        prefix:   /categorie
        
# USER ---
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile