<?php

namespace Walva\SupportkotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilleulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilleulRepository extends EntityRepository
{
}
